### ISSUE TITLE
[Request] Delivery Status

### ISSUE THREAD

**Issue by Veldkornet** [Retrospected/app.picnic#1]
If possible, could you make it possible for me to add the delivery status to some flows?

So that I can make a flow that would run:
- When an order is placed
- When something is planned for delivery (along with the delivery time)
- When something has been delivered
etc.

**Comment by Retrospected** [comment]
Thanks for your input! I was already thinking about introducing some triggers and will definitely take your ideas into account.

**Comment by Veldkornet** [comment]
Ah, that was my main reason for checking the app out ;)

**Comment by Retrospected** [comment]
fixed in commit #6d1d82fd53a87dcf3c4ce83136f6329932363f00 and pushed to the beta version 1.1.0 in the app store
