### ISSUE TITLE
Authentication Expiration

### ISSUE THREAD

**Issue by Veldkornet** [Retrospected/app.picnic#10]
I noted that after a while (not often, maybe every couple of weeks), my flows stop working. When I go check, I see that the authentication status is “Not OK”.  Adding my password again fixes everything. 

Is there any way to refresh the authentication token every so often? Or are these expirations something which is being forced by Picnic or something similar? It usually survives reboots etc, so I’m just assuming here that it’s a time limit. 

If there’s no way around this, maybe you could make an authentication status flow card so that when the authentication status changes, I can send myself a notification that I should go update it ;)

**Comment by Retrospected** [comment]
I noticed the same last week, maybe they shortened the expiration time of the authorization token. I will look into it soon.

**Comment by Retrospected** [comment]
i'm testing a fix, apparently they changed the "invalid session token" response so i've improved it... (in an ugly way)

**Comment by Retrospected** [comment]
fixed and pushed for release in 8f3fa5214f6681258a3f61cdf36523a94afd67d7
waiting for approval to update the appstore
