### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jfmulder** [Retrospected/app.picnic#12]
Sinds zo'n 2 weken werkt de Pinic app ineens niet meer.
Ik ben ingelogd, via de app, bij picnic, maar de status meldingen komen niet meer door.
Ik heb de app en de bestel status gereset, maar beide hielpen niet.

**Comment by Retrospected** [comment]
thx voor je report, het was me zelf nog niet opgevallen...
ik zie dat het bestellen van producten nog wel werkt, maar wellicht is er iets veranderd in de API. Ik ga er naar kijken!

**Comment by Retrospected** [comment]
Ik ben de fix lokaal aan het testen, maar ik wil de hele bestelcyclus even doorlopen en dat kan met de huidige drukte wel even duren: f1d69bd231f0815097867fdfe6619ca85ae026bf

**Comment by jfmulder** [comment]
Dank voor je update! Ja, het is bizar druk dus dat gaat niet zo makkelijk momenteel.

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by Retrospected** [comment]
de test is afgerond, er was nog 1 fix nodig feb3b4bf8e1628a5a7af6407841e11c40723cdb4 
nu nog even wachten tot de approval voor de update in de homey app store

**Comment by Retrospected** [comment]
De update is gepublished!

**Comment by jfmulder** [comment]
Proces doorlopen, alles werkt weer! Super, thnx!




Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________
