### ISSUE TITLE
[Feature Request] Barcode

### ISSUE THREAD

**Issue by MrBlue90** [Retrospected/app.picnic#13]
Dear developer,

Is there any change you could implement a solution so the Picnic app could handle barcode numbers?
My usecase would be having a barcode scanner in the kitchen. Once it scans a barcode, it would send the barcode number to Homey, Homey would trigger a flow to add the item with barcode x to the shopping list.

Looking forward hearing from you.

Regards

**Comment by Retrospected** [comment]
Hey MrBlue90,

I like the idea and I looked into it, however the API of Picnic does not support searching for barcodes. Unless you want to create and maintain a database of your own, matching the barcodes with the products, or know a (public) database that can do this for us, I'm afraid this will not be that easy.
