### ISSUE TITLE
App logt zich regelmatig uit.

### ISSUE THREAD

**Issue by Ranney1** [Retrospected/app.picnic#14]
App stopt regelmatig met werken, is dan uitgelogd. 
Enig idee hoe dit op te lossen? Meestal is dit elke 1-2 weken.

**Comment by Retrospected** [comment]
Bedankt voor je bericht, dit is me laatst ook opgevallen. Ik denk dat de authenticatiecode verloopt en niet correct wordt vernieuwd. Omdat ik mijn Homey voorheen elke nacht opnieuw opstarten had ik er geen last van.

Ik zal er binnenkort eens naar gaan kijken!

**Comment by Ranney1** [comment]
Haha, goede tip! Ik heb homey nu ingesteld om dagelijks de App te herstarten. Wellicht dat dat tijdelijk de oplossing is 👍

**Comment by Retrospected** [comment]
Ik heb de bug ookal gevonden denk ik, dus hoop snel een fix uit te brengen. Ik laat het weten!

**Comment by Retrospected** [comment]
Dit zou het moeten fixen, ik ga de update aanvragen voor de Homey App store https://github.com/Retrospected/app.picnic/commit/5959bd0a17635a0b64a48e2b72462a48a53c5b5d

**Comment by Retrospected** [comment]
Het lijkt nu 3 weken te werken zonder uitgelogd te raken, dus ik ga er van uit dat het gefixt is. Mocht het probleem weer opspelen laat het gerust even weten!
