### ISSUE TITLE
Deletion of the `POST /api/{api}/deliveries` endpoint

### ISSUE THREAD

**Issue by Stephan202** [Retrospected/app.picnic#15]
Hi @Retrospected! Just a heads-up: Picnic plans to drop the `POST /api/{api}/deliveries` endpoint in the coming 1-2 weeks, thereby breaking [this call](https://github.com/Retrospected/app.picnic/blob/fb1e465eafbf11941e0b1024cc1a340717947959/lib/utils.js#L122). Looking at the code, I think calling `/api/{api}/deliveries/summary` instead will work just as well for your use case, and pull way less data over the wire.

NB: it appears that the [5 minute polling interval](https://github.com/Retrospected/app.picnic/blob/fb1e465eafbf11941e0b1024cc1a340717947959/app.js#L11) happens 24/7. It might be nice to make that logic a bit smarter, e.g. by periodically (say, every 12 hours) assessing whether there are any future deliveries at all, with polling commencing e.g. only ~1/2 hours before the earliest delivery time. :)

**Comment by Retrospected** [comment]
Hi @Stephan202, thanks for reaching out! It was a matter of time before API changes would occur that would break my app, but I appreciate your timely headsup and will update it. I will take your efficiency improvement into account. I'm not a professional dev and work on this in my spare time, so bear with me, but I will see what I can do 😃.

**Comment by Retrospected** [comment]
Both the API endpoint as well as the smarter polling logic has been pushed to the prod version of the app
4b0579514db9cb7b65fa868df93ba0d07b083900

By default it polls every 12 hours; as soon as an order has been placed it polls every hour; and starting 30min before the time window of delivery, it polls every minute until the order has been delivered.
