### ISSUE TITLE
Date & Time Format in ETA

### ISSUE THREAD

**Issue by Veldkornet** [Retrospected/app.picnic#2]
I love the fact this this information is even available to Homey, but a Suggestion to adjust the way that the eta begin and eta end is done. 

Currently, it’s quite a mouthful, whether reading it as text or letting Homey announce it:

eta_start: 2018-09-15T20:15:00.000+02:00
eta_end: 2018-09-15T21:15:00.000+02:00

It would be better if this was more human like... for this, I think that the eta_begin and eta_end should only be the time, and then have a third tag for the day; and then of course make it more readable. 

So an example of the 3 values would be:
eta_start: 20:15
eta_end: 21:15
eta_date: 2018-09-15

**Comment by Retrospected** [comment]
Thanks again for your input!

fixed in commit retrospected@a022cf65622f372ec6273e2fea208af961188b91 and pushed to the beta version 1.2.0 in the app store
