### ISSUE TITLE
Feature request: compatibility for Homey Pro 2023 :)

### ISSUE THREAD

**Issue by Tweaqer** [Retrospected/app.picnic#20]
![image](https://user-images.githubusercontent.com/20989897/219177891-aa58d2cc-f3b2-42d5-af4b-c06694143f89.png)

Can you please make this app compatible for the new Homey variant? Cheers!

**Comment by Retrospected** [comment]
Yes, I started working on it this week in the [sdk3](https://github.com/Retrospected/app.picnic/tree/sdk3) branch.
I am currently testing the triggers, the actions still need some more work.

**Comment by Tweaqer** [comment]
Thats awesome! I hope to receive my Homey somewhere early next month :) Thanks for you work on the app(s)!

**Comment by Retrospected** [comment]
I finally had some time to work on this and i think the new version is now fully functional on SDK3.

I will be running it for at least 1 order-cycle of my own to verify everything works as expected ;).

The sdk3 version is published to the test channel of the app, in case you want to help me test:
https://homey.app/nl-nl/app/app.picnic/Picnic/test/
