### ISSUE TITLE
Homey 2023

### ISSUE THREAD

**Issue by Meijer21** [Retrospected/app.picnic#28]
Hoi! Hele toffe app, bedankt voor het maken. Zijn er ook plannen voor een Homey Pro 2023 update?

**Comment by Retrospected** [comment]
Jazeker. Je kan hem al installeren via het test channel in de [appstore](https://homey.app/nl-nl/app/app.picnic/Picnic/test/). Ik wacht nog op een laatste goedkeuring van Homey en dan breng ik hem op het stabiele kanaal uit, hopelijk nog begin van deze week!

**Comment by Meijer21** [comment]
Aah heel tof, dat was mij nog niet bekend. Thanks!Op 27 mrt. 2023 om 09:48 heeft Retrospected ***@***.***> het volgende geschreven:﻿
Jazeker. Je kan hem al installeren via het test channel in de appstore. Ik wacht nog op een laatste goedkeuring van Homey en dan breng ik hem op het stabiele kanaal uit, hopelijk nog begin van deze week!
