### ISSUE TITLE
Picnic app op Homey Pro 2023

### ISSUE THREAD

**Issue by eppw1970** [Retrospected/app.picnic#38]
Hoi,

Ik heb pas geleden een Homey Pro 2023 aangeschaft, en hierop o.a. de PicNic app geïnstalleerd.
Installatie gaat goed. En ook het account invullen geeft geen probleem.
Alleen lukt het niet om de triggers te laten werken, zelfs een eenvoudige flow waarbij "Boodschappen zijn bezorgd"  waarbij een pushnotificatie naar mijn mobiel gestuurd word met alleen een tekst, lijkt niet getriggerd te worden.

Ben ik nog iets vergeten in te stellen?

**Comment by Retrospected** [comment]
Hey, ik zag je diagnostic report zojuist. Ik kan daar niets geks uit opmaken. Staat je authenticatie status wel op OK in de instellingen van de app?

**Comment by eppw1970** [comment]
Bedankt voor je reactie.
Authenticatiestatus staat op OK.

Ik zal op de volgende bestelling moeten wachten om verdere checks te doen.
Ik heb de volgende Homey Pro 2023 flows klaar staan:


￼

Met vriendelijke groet,

Eric Wijdeman

**Comment by Retrospected** [comment]
In het 'bestelling status' veld in de instellingen zou de laatste status zichtbaar moeten zijn. Let wel dat het bij het plaatsen van een bestelling tot 12 uur kan duren voordat deze update.

**Comment by Retrospected** [comment]
@eppw1970 is het ondertussen gelukt?

**Comment by eppw1970** [comment]
Ja, is ondertussen gelukt. Alles verwijderd en opnieuw aangemaakt. Nu werkt het.  Dank voor je hulpVerstuurd vanaf mijn iPadOp 9 nov 2023 om 19:44 heeft Retrospected ***@***.***> het volgende geschreven:﻿
@eppw1970 is het ondertussen gelukt?
