### ISSUE TITLE
Add product to basket not working

### ISSUE THREAD

**Issue by ThaYoung1** [Retrospected/app.picnic#41]
When I add a product to my basket with the action card, everything seems to be gone right from Homeys perspective (green check after executing the flow).

But the product does not appear in the basket in the PicNic App.

**Comment by Retrospected** [comment]
Thanks for reporting, something must have changed on the API side of Picnic i guess. I will try to find some time to debug and fix it

**Comment by Retrospected** [comment]
@ThaYoung1 it seems like i fixed it, could you test this out for me? https://homey.app/a/app.picnic/test/

**Comment by ThaYoung1** [comment]
Hi @Retrospected, it works now. Thanks for the fix.
