### ISSUE TITLE
App Keeps Crashing

### ISSUE THREAD

**Issue by Veldkornet** [Retrospected/app.picnic#5]
Since the weekend, the app keeps crashing. 

It says that you’ve been informed, so I assume you have ;)

Not sure what else I can tell you since it doesn’t give me much info...

**Comment by Retrospected** [comment]
Thanks for your message, i noticed the same just a couple days before the weekend. This has to do with the fact that the authentication key is valid for 30 days. I improved the authentication function storing the username and password in Homey and re-authenticating when the session has been expired. I've pushed this yesterday in commit retrospected@b69acd14c05bd4640e7d1fd0cf94760c6e097efe.

The update (version 1.3.0) is currently under review by Athom before it's pushed to the app store. Closing this issue assuming this will fix it, please let me know if it didn't.

**Comment by Retrospected** [comment]
I'm still waiting for the update to be approved, until that time you can temporarily solve the issue by logging in to Picnic again via Homey's settings. This should give you another 30 days :)
