### ISSUE TITLE
Notifications in 1.3.0 stopped

### ISSUE THREAD

**Issue by Veldkornet** [Retrospected/app.picnic#6]
Since the app updated to 1.3.0, my flows which let you know if something was ordered, the delivery time etc all stopped working. 

I checked in the settings and it says that the authentication status is OK. 

I also tried to see if I could see anything in Homey Logger, but I could t see anything at all from Picnic. 

It looks as though the flows are no longer being triggered. 

Any ideas?

**Comment by Retrospected** [comment]
Hmm that’s strange, i dont have the issue here. Did your already go through every possie state? Because it might be stuck on one of the states since the last authentication bug. In that case it should resolve itself upon the next state change of your order.

**Comment by Veldkornet** [comment]
I re-installed 1.2 last week just in time for it to send the “delivered” notification. Then in the week it updated to 1.3. 

I’ve now been passed the “ordered” and “binnenkort” triggers without anything happening. Later today, the “delivered” one should be triggered so I can confirm later.

**Comment by Veldkornet** [comment]
Nope, nothing...

**Comment by Retrospected** [comment]
stupid mistake.. I didn't properly debug the version installed/updated from the appstore

Fixed in retrospected@3f7b19928b7f9b42d7da5f2ee0d7736aa4a2046e, pushing it to the appstore but this might take a few days again unfortunately.

**Comment by Veldkornet** [comment]
Cool, no worries 😎 I’ll wait for the update then

**Comment by Retrospected** [comment]
It should be published and fixed in version 1.3.1, let me know if it isn’t.

**Comment by Veldkornet** [comment]
For me it’s still not working :(

**Comment by Veldkornet** [comment]
Woop, started working today!

I just re-entered the credentials now it seems okay.

**Comment by Retrospected** [comment]
Yea that must’ve been it i guess. Can’t really think of a reason why it wouldn’t work.

I have been getting some crash reports lately but those are related to poor (/no) exception handling.. i hope i have time to look in to that this week
