### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Veldkornet** [Retrospected/app.picnic#8]
Picnic crashed all of a sudden and won’t start back up...

![6C9844FA-1814-42E3-881E-D710ADF329F6](https://user-images.githubusercontent.com/10297361/55822933-eadd2580-5b00-11e9-9572-eb5aca1510c4.jpeg)

**Comment by Retrospected** [comment]
I noticed, it happened to all users.. probably a change in the api of picnic :(.. i’ll try to have a look at it later this week

**Comment by Veldkornet** [comment]
Seems to have started working again, so...

¯\(°_o)/¯
